Update Ubuntu build server version
Update to Ubuntu 2022.07.2 - CircleCI right now is giving an
error: "Resource class machine for xlarge, image ubuntu-2204:2022.07.1
is not available for your project, or is not a valid resource class."