Update CircleCI config to use new GH org. (#2028)
* Update CircleCI config to use new GH org.

* Revert changes to chart references - we have not migrated those

* Update Ubuntu build server version

Update to Ubuntu 2022.07.2 - CircleCI right now is giving an
error: "Resource class machine for xlarge, image ubuntu-2204:2022.07.1
is not available for your project, or is not a valid resource class."

* Switch 'xlarge' resource classes to 'large'.

The 'armadaproject' is currently on the CircleCI free plan,
which allows only s-l sized resource specifications.

* Revert prior change Ubuntu 2022.07.2 version back to 2022.07.1