fix: mage ui target trying to change to an invalid dir (#4481)
#### What type of PR is this?

Fix broken mage target.

#### What this PR does / why we need it:

`mage ui` was reporting:
```
Error: chdir internal/lookoutui: no such file or directory
```

The yarnRun function in `magefiles/yarn.go` had an incorrect path - it
was trying to return to the wrong directory level after changing into
`internal/lookoutui`

Signed-off-by: Dejan Zele Pejchev <pejcev.dejan@gmail.com>